import * as mongoose  from 'mongoose';
export enum TYPE_STATUS_MANGA {
    ON_GOING=0,
    COMPLETE=1
}
export enum MANGA_TYPE {
    MANGA_BATO="MANGA_BATO"
}
export const mangaSchema:mongoose.Schema = new mongoose.Schema({
    name:String,
    author:String,
    category:[
        {type:String}
    ],
    image:String,
    views:{
        type:Number,
        default:0
    },
    description:String,
    url:String,
    manga_status:{
        type:Number,
        default:TYPE_STATUS_MANGA.ON_GOING
    },
    chapters:[
        {type:mongoose.Types.ObjectId,
        ref:'chapter'}
    ],
    chapter_update:{
        type:Date,
        default:Date.now
    },
    enable:{
        type:Boolean,
        default:true
    },
    source:{
        type:String,
        default:MANGA_TYPE.MANGA_BATO
    },
    devices:[
        {
            type:String
        }
    ]
},{timestamps:true})
export interface Manga extends mongoose.Document {
    name?:string,
    author?:string,
    image?:string,
    views?:string,
    url?:string,
    manga_status?:number,
    enable?:boolean,
    description?:string,
    category?:Array<string>,
    chapters?:Array<string>,
    chapter_update?:Date,
    source?:string,
    devices?:Array<string>
}